### ISSUE TITLE
Support declarative config

### ISSUE THREAD

**Issue by rpanderson** [chrisjbillington/setuptools-conda#1]
This proposal is to provide the option to specify the `dist_conda` dictionary in setup.cfg, e.g.
```ini
[dist_conda]
pythons = 3.6, 3.7, 3.8
platforms = linux-64, win-32, win-64, osx-64
force_conversion = True
```
This follows the convention of `command_options` entries getting their own section in setup.cfg.

**Comment by rpanderson** [comment]
This is already supported by setuptools_conda which conforms to the extensibility specification of setuptools :-P

**Comment by rpanderson** [comment]
The conditional definition of e.g. `INSTALL_REQUIRES` in [setup.py of this package](https://github.com/chrisjbillington/setuptools_conda/blob/master/setup.py#L22) can use requirements from setup.cfg and override as follows:
```python
if "CONDA_BUILD" not in os.environ:
    dist = Distribution()
    dist.parse_config_files()
    INSTALL_REQUIRES = dist.command_options["options"]["install_requires"][1]
    INSTALL_REQUIRES = INSTALL_REQUIRES.strip().split('\n')
else:
    INSTALL_REQUIRES = []

...

setup(
    ...
    install_requires=INSTALL_REQUIRES
)
```

It would probably be nicer to do this without the additional parsing above, e.g.
```python
from setuptools.dist import Distribution

dist = Distribution()
dist.parse_config_files()
dist.parse_command_line()
if "CONDA_BUILD" in os.environ:
    dist.command_options["options"]["install_requires"] = ("setup.cfg", [])

...

setup(
    ...
    command_options=dist.command_options
)
```
However, this did not work, raising `distutils.errors.DistutilsArgError: invalid command 'dist_conda'` when calling `python setup.py dist_conda -h`, for example.

**Comment by rpanderson** [comment]
Actually, the parsing of `platforms` doesn't seem to behave the same way as other attributes in setup.cfg. 

1. This failed:
```ini
[dist_conda]
platforms = linux-64, win-32, win-64, osx-64
```
... with:
```python-traceback
ValueError: Invalid platform list ['linux-64', ' win-32', ' win-64', ' osx-64']
```

2. This failed:
```ini
[dist_conda]
platforms = 
  linux-64
  win-32
  win-64
  osx-64
```
... with:
```python-traceback
ValueError: Invalid platform list ['\nlinux-64\nwin-32\nwin-64\nosx-64']
```

The only valid way to specify `platforms` was comma-separated, no-whitespace:
```ini
[dist_conda]
platforms = linux-64,win-32,win-64,osx-64
```

**Comment by chrisjbillington** [comment]
The parsing seems to be based on what I did manually in setuptools_conda parsing command line args, which I assumed are comma-delimited since it's normal for command line args not to have spaces. I can easily make it strip() the results so that whitespace is ignored too.

**Comment by chrisjbillington** [comment]
As of 548e8333597b41ca0914c745104cad86fef7db1a, arguments may be newline delimited and have extra whitespace around them

**Comment by rpanderson** [comment]
Thanks, @chrisjbillington! Can you anticipate which version this will this be in?

*Update*: Never mind, it's not a declared requirement for what we're working on.

**Comment by chrisjbillington** [comment]
Well, your current PRs have spaces around the python versions, so they need this :p

I'll release a new `setuptools_conda` once I've

a) Made it include entry_points in the recipe
b) Made it be able to output a recipe pointing at PyPI instead of building on the spot from a local sdist (though I guess this can wait).
