### ISSUE TITLE
Don't require setup.py if setup.cfg is present

### ISSUE THREAD

**Issue by bilderbuchi** [chrisjbillington/setuptools-conda#10]
First, let me says that this looks like a great tool to bridge the conda and vanilla python packaging worlds, thank you! 👏 

Setuptools/pip does not anymore require a setup.py file (if setup.cfg is present). This is reflected in the documentation, e.g. [here](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html).

I noticed that, in contrast, setuptools-conda requires a setup.py file. If no setup.py is present, when `setuptools-conda.exe build .` runs python.exe setup.py dist_conda, it fails with "[Errno 2] No such file or directory".

If run `pip install -e .` in the same directory, it completes successfully without issue.

```
pip install -e .
Obtaining file:///blabla/python_template
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: demo
  Running setup.py develop for demo
Successfully installed demo-0.1
```
Do you need a more precise repro procedure, or is this sufficient?

**Comment by chrisjbillington** [comment]
It would be good to support projects without a setup.py. But setuptools-conda is implemented as a distutils command dist_conda, that is called as `python setup.py dist_conda`. Do you know if there is a way to call custom distutils commands via e.g. pip for projects that lack a setup.py?

Otherwise I'm thinking one approach could be to temporarily create a stub setup.py

**Comment by chrisjbillington** [comment]
I think I was reading some code deep in pip or similar that essentially ran a setup.py stub in a little isolated `exec()` or `runpy` call without creating a file on disk. I'll check out what they do, seuptools-conda can probably do the same.

**Comment by bilderbuchi** [comment]
You're probably right --  in the log output above you see that pip says "Running setup.py develop for demo", so it probably creates one itself.

**Comment by bilderbuchi** [comment]
Indeed, the code in pip to create a shim file can be found [here](https://github.com/pypa/pip/blob/0b6316cd78d07bcb045a13ec464524c72ddcf520/src/pip/_internal/utils/setuptools_build.py#L4-L18). That file also contains a number of functions `make_setuptools_<command>_args`, so maybe something along those lines will also be necessary to define for `dist_conda`?

**Comment by bilderbuchi** [comment]
Huh, interesting. I just realised that `pip install -e .` without a setup.py file present *only* works if a pyproject.toml is present (even if empty), otherwise I get "ERROR: File "setup.py" not found for legacy project". I think this is as it "should" be, see discussion at https://github.com/pypa/pip/pull/9945 (danger: rabbit hole!)

**Comment by chrisjbillington** [comment]
Thanks for the pointer to pip's shim. I went ahead and did something similar, and I'm pretty happy with it. Let me know if there are any issues.

**Comment by bilderbuchi** [comment]
Thanks for the quick fix, this works now!
