### ISSUE TITLE
install-requirements fails when not finding *.egg-info file

### ISSUE THREAD

**Issue by bilderbuchi** [chrisjbillington/setuptools-conda#11]
When running install-requirements, I get a failure (on Windows):
```
$ setuptools-conda.exe install-requirements .

Getting build requirements...
Using build requirements from [build-system]/requires
No name differences
No extra channels
[running]: conda install -y wheel setuptools
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


Getting run requirements...
[running]: C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\python.exe setup.py --name
No name differences
[running]: C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\python.exe setup.py egg_info
Traceback (most recent call last):
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\Scripts\setuptools-conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\site-packages\setuptools_conda\__main__.py", line 383, in main
    run_requires = get_run_requires(proj, additional_args, project_name)
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\site-packages\setuptools_conda\__main__.py", line 257, in get_run_requires
    requires = requires_file.read_text().splitlines()
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\pathlib.py", line 1256, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'my_package.egg-info\\requires.txt'
```

If I leave off the `.` at the end of the command (the README and CLI help text are a bit ambiguous if I need that or not), this fails even earlier with an unrelated error message:
```
$ setuptools-conda.exe install-requirements

Getting build requirements...
Traceback (most recent call last):
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\Scripts\setuptools-conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\u1ac_cbu\AppData\Local\mambaforge\envs\packaging_playground\lib\site-packages\setuptools_conda\__main__.py", line 356, in main
    channels = get_channels(proj, additional_args)
UnboundLocalError: local variable 'proj' referenced before assignment
```
Note that `setuptools-conda.exe build .` completes successfully.

What am I doing wrong?

**Comment by chrisjbillington** [comment]
The `UnboundLocalError` is a bug handling command line args - you are supposed to put the `.` at the end of the command. Thanks for that, will fix.

The error you're getting when entering the command correctly I'm less sure about. The way `setuptools-conda` gets the run requirements of the package is by running `python setup.py egg_info` and then inspecting what is supposed to be a resulting file `my_package.egg-info\requires.txt`. This is how other tools do it too, so ought to be pretty standard, we're not doing anything weird.

Could you let me know if after running`setuptools-conda install-requirements .`, the folder `my_package.egg-info` exists, and if so, if anything is in it? Perhaps it is a single file instead of a folder.

If it doesn't exist, could you try running `python setup.py egg_info` manually, and seeing if that successfully outputs `my_package.egg-info\requires.txt`?

Could you perhaps show the contents of your `setup.py`? I don't know what I might be looking for there, but am wondering if something might jump out. If it is not actually a valid `setup.py` and does not call `setuptools.setup()`, for example, that would explain it!

**Comment by bilderbuchi** [comment]
Both `setuptools-conda.exe install-requirements .` and `python setup.py egg_info` create a `my_package.egg-info` directory with a couple files, but no `requires.txt` -- I strongly suspect this could be because I don't (yet) have any `install_requires` defined in `setup.cfg`. 
This is I think one constellation that is probably not accounted for yet.

If I add a dependency (e.g. numpy), both commands also create a requires.txt, but `setuptools-conda.exe install-requirements .` still fails with the same error. 
In this case I suspect that the problem is that I have a [src-based layout](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure), so the file is in `python_project_template\src\my_package.egg-info\requires.txt` - I think the code looks in the wrong directory [here](https://github.com/chrisjbillington/setuptools-conda/blob/889c4093613a9885d7f0508137d8db76c05e3cce/setuptools_conda/__main__.py#L257)?

**Comment by bilderbuchi** [comment]
Ah, setup.py is only minimal (cf. #10)
```
import setuptools
setuptools.setup()
```

**Comment by chrisjbillington** [comment]
Excellent, so it doesn't work:

* For a src-based layout, in which case the requirements file is in an unexpected location, or
* If there are no requirements listed, in which case the requirements file isn't produced.

That's very clear, should be able to fix these issues easily enough.

**Comment by chrisjbillington** [comment]
The `UnboundLocalError` should be fixed in 7701e88678989f22175c74c29279e9dfdb0d703b

**Comment by chrisjbillington** [comment]
src-based layout and the case of there being no requirements.txt generated should be fixed in 8297754

**Comment by bilderbuchi** [comment]
Great, Thanks!

**Comment by bilderbuchi** [comment]
Thanks for the fix, both things work now! 
Note that the help text for `setuptools-conda install-requirements` reproduced in the README needs a small change to reflect that projects is now mandatory at least once: ` projects [projects ...]`

Do you plan on pushing out a (bugfix) release soonish? I'd just like to know if I can already start updating instruction materials with using setuptools-conda.

**Comment by chrisjbillington** [comment]
Good to hear!

Yes, I do plan on making a bugfix release soon, no reason not to, just gonna fix the CI. If I don't do it within a few days feel free to remind me!

**Comment by chrisjbillington** [comment]
v0.10.0 is building now
