### ISSUE TITLE
conda fails to install setuptools-conda

### ISSUE THREAD

**Issue by sethfri** [chrisjbillington/setuptools-conda#17]
Hi there, for some reason `conda` fails to install `setuptools-conda`, despite me running the command in the README. Here's the output I'm getting:

```
~/Developer/fastconda master * conda install -c labscript-suite setuptools-conda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - setuptools-conda

Current channels:

  - https://conda.anaconda.org/labscript-suite/osx-arm64
  - https://conda.anaconda.org/labscript-suite/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I searched Anaconda, and I _am_ seeing that `setuptools-conda` exists [here](https://anaconda.org/labscript-suite/setuptools-conda), so I'm not sure why this is happening. I tried with `mamba` as well instead of `conda` and got the same issue. Would you mind taking a look @chrisjbillington?

I'm brand new to the conda and Python worlds so apologies if I'm missing anything obvious!

**Comment by sethfri** [comment]
Navigating into the two channels linked from Conda (https://conda.anaconda.org/labscript-suite/osx-arm64 and https://conda.anaconda.org/labscript-suite/noarch), it actually _doesn't_ look like `setuptools-conda` is there. Not sure why though

**Comment by chrisjbillington** [comment]
Hi Seth,

it's because it isn't built for osx-arm64, so there isn't a package available for your OS and architecture.

You would need to build it from source, instructions for which are available in the README.

I believe GitHub actions (which I use to build packages) may now have support for OSX on ARM, so I might be able to start building for that architecture myself. Until then, ARM mac users will have to build it themselves, sorry!

**Comment by sethfri** [comment]
@chrisjbillington Thanks for the quick reply! My mistake, I was reading `x64` in the GitHub Action workflow as `arm64`. That makes sense!
