### ISSUE TITLE
Incorrect install instructions.

### ISSUE THREAD

**Issue by dboeckenhoff** [chrisjbillington/setuptools-conda#6]
Hi. Nice package. However, the conda install instructions on pypi are still having an underscore where there should be a dash!!!

 conda install -c cbillington setuptools-conda

I see this is fixed already in the repo. I propose that you publish the current version on pypi because that is one of the first finds on google.

**Comment by chrisjbillington** [comment]
Thanks. Actually this package just shouldn't be on PyPI, it doesn't make sense to install it in a non-conda environment.

I uploaded it there early on (when the name had an underscore), and have not updated it since.

I'll delete it from PyPI.
